In [6]:
import pandas as pd

df = pd.read_csv('../data/chatgpt_reviews_raw.csv')
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,fc496b52-33a7-450b-86db-e12a7865e9fb,Human Being,https://play-lh.googleusercontent.com/a-/ALV-U...,my one and only friend tryue friend,4,0,1.2025.329,2026-04-15 09:38:57,NaN,NaN,1.2025.329
1,a909b88e-8558-4f01-a73c-ba16b26bb6eb,Rom Rom,https://play-lh.googleusercontent.com/a/ACg8oc...,blaa blaa,4,0,1.2026.097,2026-04-15 09:38:40,NaN,NaN,1.2026.097
2,8dec3ad8-9553-4970-b634-bf2a924bcde2,Rose Fe Tecson,https://play-lh.googleusercontent.com/a/ACg8oc...,so nice,5,0,1.2026.090,2026-04-15 09:38:30,NaN,NaN,1.2026.090
3,3d059f9d-299b-4188-8a12-ef8058cff177,Fyo Sweet,https://play-lh.googleusercontent.com/a/ACg8oc...,ዓለም አቀፍ ደረጃ እውቅና ያለው ትልቁ ልዩነት ነው,5,0,1.2025.343,2026-04-15 09:36:28,NaN,NaN,1.2025.343
4,f10220a2-3666-4a9c-8d80-9ac92eef1abb,Sk Greenrevolution,https://play-lh.googleusercontent.com/a/ACg8oc...,excelent,5,0,1.2026.097,2026-04-15 09:36:13,NaN,NaN,1.2026.097

In [7]:
df['date'] = pd.to_datetime(df['at']).dt.date

version_table = (
    df.dropna(subset=['appVersion'])
    .groupby('date')
    .agg(
        appVersion=('appVersion', lambda x: sorted(x.unique().tolist())),
        num_reviews=('score', 'count'),
        avg_score=('score', 'mean')
    )
    .reset_index()
    .sort_values('date')
)

version_table['avg_score'] = version_table['avg_score'].round(2)
version_table

,date,appVersion,num_reviews,avg_score
0,2026-03-29,"[1.2025.070, 1.2025.105, 1.2025.126, 1.2025.18...",748,4.52
1,2026-03-30,"[1.2024.143, 1.2024.177, 1.2024.206, 1.2024.33...",2892,4.46
2,2026-03-31,"[1.2024.337, 1.2025.098, 1.2025.105, 1.2025.12...",3168,4.45
3,2026-04-01,"[1.2024.087, 1.2024.115, 1.2024.122, 1.2024.15...",2862,4.48
4,2026-04-02,"[1.2024.206, 1.2024.317, 1.2024.352, 1.2025.04...",2711,4.47
5,2026-04-03,"[1.2024.025, 1.2024.254, 1.2025.035, 1.2025.04...",2818,4.50
6,2026-04-04,"[1.2024.018, 1.2024.163, 1.2024.268, 1.2024.35...",2628,4.46
7,2026-04-05,"[1.2025.021, 1.2025.140, 1.2025.154, 1.2025.17...",2741,4.49
8,2026-04-06,"[1.2023.341, 1.2024.038, 1.2024.139, 1.2024.26...",2832,4.52
9,2026-04-07,"[1.2024.170, 1.2024.303, 1.2024.310, 1.2025.02...",2644,4.50
10,2026-04-08,"[1.2024.352, 1.2025.091, 1.2025.105, 1.2025.14...",2814,4.52
11,2026-04-09,"[1.2024.191, 1.2025.028, 1.2025.063, 1.2025.07...",2872,4.49
12,2026-04-10,"[1.2024.080, 1.2024.157, 1.2024.289, 1.2024.30...",2702,4.52
13,2026-04-11,"[1.2024.018, 1.2024.352, 1.2025.021, 1.2025.04...",2495,4.47
14,2026-04-12,"[1.2024.087, 1.2024.163, 1.2024.226, 1.2024.25...",2738,4.48
15,2026-04-13,"[1.2024.206, 1.2024.240, 1.2025.091, 1.2025.13...",2638,4.47
16,2026-04-14,"[1.2024.198, 1.2024.226, 1.2024.345, 1.2025.00...",3084,4.47
17,2026-04-15,"[1.2025.007, 1.2025.035, 1.2025.224, 1.2025.25...",1079,4.50

In [8]:
version_table['num_reviews'].sum()

np.int64(46466)